travis:
  secure:
    BINSTAR_TOKEN: FYRvtnFTzbyXln7ATjDFpi+Vcu0dbA5y8Kw2uGFO7XCQP+GNosYieDVehCy9PFaKmqrkccxZyqdQr1jMxWjAbMDq4Lie9bWoPFEIC+2LBGzBYuZl2U33NPUPfE5ZUXqlmxbJ4NKJn0GF3EbNqtPHIhw+JoNzFXIDEETKxwgBZM4AU72P2acpuIF/znymxPT8IOfks7Tze3+Tf5QQRaDebFKVbakXW4SJpeYDkDClVVMxlYAsnEgnZnn/asZeJidGYlC1QuoITSWoaBjz8Zrm3kz/dlmhQkbpPaSuRLZjZCUwO4jiHcfGU9fZ/qAUewOp4Sog/Rd5gSmVVIkqhPsiIHfO24DKHoIOoraMebzvWX3jSLqnko3h2TPGyhrtzX0JadHSHEB6p/ZMl206Vpzyc5ukk3FwNE3y41oOPaIY9yq8wlCiqLKXNakig9LbQAljia94ABhCl/M17MmajyCtYaQoCPYKyv0rxNBjD2//oEV2Oa+GihfQjs/bEIPbbTGBn/wztVdX+G2VF+IGPHiGshZKwer0tUGCmU/c5HXVrkyooFHt1aZbzsQy/QWyIrXw4YR7xAl16VjJbtTHaZ5PRL6eaJAU/PlUSBQfil2Q3suvY3mXAi9vp1WQ2Z98k6r6XRtZh0ew+roGz23dn2JTwjZXOxcoolY1LnSxX34tA+M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
